spring:
  application:
    name: hello
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 20s
      host: localhost
      port: 8500


management:
  endpoints:
    web:
      exposure:
        include: health,info